name: 'Bikeclub Webform nodes'
description: 'Provides Webform Node content type.'
type: 'Content type'
recipes:
  - bikeclub_content_type_base
  - bikeclub_media
  - bikeclub_banner
install:
  # Core
  - menu_ui
  # Contrib.
  - honeypot
  - scheduler
  - webform_node
config:
  strict: false
  actions:
    user.role.site_admin:
      createIfNotExists:
        label: 'Site administrator'
      grantPermissions:
        - 'create webform content'
        - 'delete any webform content'
        - 'edit any webform content'
        - 'use text format basic_html'
        - 'use text format summary_fields'
