name: 'Bikeclub Webform nodes'
description: 'Adds a Webform content type. This is useful if a single webform is used multiple times. E.g., a volunteer sign-up webform is used every year. Include it in a new webform page each year and results for each year are available on the webform page.'
type: 'Content type'
recipes:
  - bikeclub_banner
  - bikeclub_content_type_base
  - bikeclub_registration_field_storage
install:
  # Contrib.
  - honeypot
  - webform
  - webform_node
  - webform_options_limit
  - webform_templates
  - webform_ui
  - webform_views
config:
  strict: false
  actions:
  # 'Webform' vs 'Webform content' - the latter refers to nodes.
    user.role.events_coordinator:
      createIfNotExists:
        label: 'Events coordinator'
      grantPermissions:
        - 'access own webform configuration'
        - 'access webform help'
        - 'access webform overview'
        - 'create webform'
        - 'create webform content'
        - 'delete own webform'
        - 'delete any webform content'
        - 'edit own webform'
        - 'edit any webform content'
        - 'use text format basic_html'
        - 'use text format summary_fields'
    user.role.site_admin:
      createIfNotExists:
        label: 'Site administrator'
      grantPermissions:
        - 'access own webform configuration'
        - 'access webform help'
        - 'access webform overview'
        - 'create webform'
        - 'create webform content'
        - 'delete own webform'
        - 'delete any webform content'
        - 'edit own webform'
        - 'edit any webform content'
        - 'use text format basic_html'
        - 'use text format summary_fields'
