name: 'Bikeclub Webform nodes'
description: 'Adds a Webform content type. This is useful if a single webform is used multiple times. E.g., a volunteer sign-up webform is used every year. Include it in a new webform page each year and results for each year are available on the webform page.'
type: 'Content type'
recipes:
  - bikeclub_banner
  - bikeclub_content_type_base
  - bikeclub_field_storage_webform
install:
  # Contrib.
  - honeypot
  - webform
  - webform_node
  - webform_options_limit
  - webform_templates
  - webform_ui
  - webform_views
config:
  strict: false
  actions:
    user.role.site_admin:
      createIfNotExists:
        label: 'Site administrator'
      grantPermissions:
        - 'create webform content'
        - 'delete any webform content'
        - 'edit any webform content'
        - 'use text format basic_html'
        - 'use text format summary_fields'
